Feature/43 Implement a validation on the booking creation of a Pet
gii-is-psg2/PSG2-2021-G2-23 pull request #59
Opened 2021-04-23 10:05 UTC by estsvq

Este si.

2021-04-26 12:15 UTC, Jacgarvel requested changes

2021-04-26 12:15 UTC, Jacgarvel commented on src/main/java/org/springframework/samples/petclinic/service/ReservationService.java
> +    	Boolean reservaHecha = reservas.stream()
El código sí esta bloqueando el hecho de que una reserva no se pueda producir el mismo día con la misma mascota aunque no se muestra un mensaje de error de que las fechas coinciden. Estaría bien añadir un mensaje de error

2021-04-26 12:15 UTC, Jacgarvel commented on src/main/java/org/springframework/samples/petclinic/model/Reservation.java
> +    @FutureOrPresent(message = "La fecha debe ser presente o futura")
Hay un problema con la validación de las fechas y es que la fecha inicio puede ser posterior a la fecha fin
(Por ejemplo fecha inicio: 30/04/2021 fecha fin: 27/04/2021). Para esto una anotación personalizada o un validador aparte es mucho más fácil. Si decides hacer un validador aparte, en este tienes que validar todo de nuevo

2021-04-26 12:15 UTC, Jacgarvel commented on src/main/java/org/springframework/samples/petclinic/web/BusyReservationException.java
> +	/**
La excepción salta adecuadamente, pero no hay ningún mensaje reflejado en la aplicación

2021-04-26 20:00 UTC, estsvq commented
Commit hecho, solicito revisión de nuevo

2021-04-26 20:30 UTC, pabgonmon2 requested changes
Falta esa etiqueta a las fechas (@NotNull) y estaría perfecto.

2021-04-26 21:17 UTC, estsvq commented
A la tersera va la vensida @NotNull incluido.,

2021-04-27 09:26 UTC, pabgonmon2 approved these changes
Todo correcto

2021-04-27 09:26 UTC, pabgonmon2 approved these changes

2021-04-27 09:30 UTC, Jacgarvel approved these changes

2021-04-27 09:31 UTC, merged